local json = require("json")
local claude_json = require("source.claude_json")
local credentials = require("source.credentials")

local function write(path, content)
	local f = assert(io.open(path, "w"))
	f:write(content)
	f:close()
	return path
end

describe("json.decode strings", function()
	it("decodes escapes and plain runs", function()
		assert_eq(json.decode('"a\\"b\\\\c\\/d\\n\\tе"'), 'a"b\\c/d\n\t\208\181')
		assert_eq(json.decode('""'), "")
		assert_eq(json.decode('"\\u00e9x"'), "\195\169x")
	end)
	it("decodes surrogate pairs", function()
		assert_eq(json.decode('"\\ud83d\\ude00"'), "\240\159\152\128")
		assert_eq(json.decode('"\\uD83D\\uDE00!"'), "\240\159\152\128!")
	end)
	it("maps unpaired surrogates to U+FFFD", function()
		assert_eq(json.decode('"\\ud83d"'), "\239\191\189")
		assert_eq(json.decode('"\\ude00x"'), "\239\191\189x")
		assert_eq(json.decode('"\\ud83d\\u0041"'), "\239\191\189A")
		assert_eq(json.decode('"\\ud83d\\ud83d\\ude00"'), "\239\191\189\240\159\152\128")
	end)
	it("rejects bad strings", function()
		assert_error(function()
			json.decode('"abc')
		end)
		assert_error(function()
			json.decode('"a\nb"')
		end)
		assert_error(function()
			json.decode('"\\x"')
		end)
		assert_error(function()
			json.decode('"\\u12"')
		end)
	end)
	it("decodes long strings", function()
		local big = string.rep("abcdefghij", 50000)
		assert_eq(json.decode('"' .. big .. '\\n"'), big .. "\n")
	end)
end)

describe("json.decode_at", function()
	it("decodes one value and returns the next index", function()
		local s = '{"x": 1, "k":  {"a": [1, 2]} , "y": 2}'
		local v, nxt = json.decode_at(s, 14)
		assert_eq(v.a[2], 2)
		assert_eq(s:sub(nxt, nxt), " ")
		local str, n2 = json.decode_at('"hi"garbage', 1)
		assert_eq(str, "hi")
		assert_eq(n2, 5)
	end)
end)

describe("source.claude_json", function()
	it("reads only the cached object from a large file", function()
		local filler = string.rep('{"p":"' .. string.rep("x", 100) .. '"},', 2000)
		local cached = '{"fetchedAtMs": 5, "utilization": {"five_hour": {"utilization": 3}}}'
		-- The trailing garbage proves the rest of the file is never decoded.
		local path = write(
			"spec/tmp/claude_big.json",
			'{"projects": [' .. filler .. '{}], "cachedUsageUtilization" : ' .. cached .. ', "z": [}'
		)
		local cu = claude_json.read(path)
		assert_eq(cu.fetchedAtMs, 5)
		assert_eq(cu.utilization.five_hour.utilization, 3)
	end)
	it("prefers the top-level key over a nested one", function()
		local path = write(
			"spec/tmp/claude_nested.json",
			'{"projects":{"p":{"cachedUsageUtilization":{"fetchedAtMs":1,"utilization":{"n":1}}}},'
				.. '"cachedUsageUtilization":{"fetchedAtMs":2,"utilization":{"five_hour":5}}}'
		)
		assert_eq(claude_json.read(path).fetchedAtMs, 2)
	end)
	it("reads the fixture", function()
		local cu = claude_json.read("spec/fixtures/claude_json.json")
		assert_true(type(cu.utilization) == "table")
	end)
	it("falls back to a full decode and rejects bad values", function()
		local path = write("spec/tmp/claude_odd.json", '{"cachedUsageUtilization": 1}')
		assert_nil(claude_json.read(path))
		path = write("spec/tmp/claude_none.json", '{"other": 1}')
		assert_nil(claude_json.read(path))
		assert_nil(claude_json.read("spec/tmp/does-not-exist.json"))
	end)
end)

describe("source.credentials expiry", function()
	it("returns plan fields alongside the expiry error", function()
		local c, err, partial = credentials.read("spec/fixtures/credentials_expired.json", 1758560000)
		assert_nil(c)
		assert_eq(err.code, "unauthorized")
		assert_eq(partial.subscription, "pro")
		assert_nil(partial.token)
	end)
	it("treats a token expiring within 60 s as expired", function()
		local path = write(
			"spec/tmp/creds_soon.json",
			'{"claudeAiOauth": {"accessToken": "T", "expiresAt": 1000000060, "subscriptionType": "max", "rateLimitTier": "t"}}'
		)
		local c, err, partial = credentials.read(path, 1000000000)
		assert_nil(c)
		assert_eq(err.code, "unauthorized")
		assert_eq(partial.tier, "t")
		c, err = credentials.read(path, 1000000000 - 1)
		assert_eq(c.token, "T")
		assert_nil(err)
	end)
end)
